development: &default
  adapter: postgresql
  database: rails-glucosejournal_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  password: coolkatt
  username: postgres

test:
  <<: *default
  database: rails-glucosejournal_test
